import { InventoryItem, ItemStatus } from '../types';

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: '1',
    name: '아두이노 우노 R3',
    category: '마이크로보드',
    quantity: 45,
    location: '수납장 A-1',
    status: ItemStatus.IN_STOCK,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    school: '대건고',
    notes: '기본 키트 포함',
  },
  {
    id: '2',
    name: '초음파 센서 HC-SR04',
    category: '센서',
    quantity: 12,
    location: '수납장 B-2',
    status: ItemStatus.LOW_STOCK,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    school: '대건고',
    notes: '',
  },
  {
    id: '3',
    name: '서보 모터 SG90',
    category: '단품',
    quantity: 0,
    location: '수납장 B-3',
    status: ItemStatus.OUT_OF_STOCK,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 24 * 10).toISOString(),
    school: '신송고',
    notes: '다음주 입고 예정',
  },
  {
    id: '4',
    name: '라즈베리 파이 4 (4GB)',
    category: '마이크로보드',
    quantity: 8,
    location: '수납장 A-2',
    status: ItemStatus.LOW_STOCK,
    lastUpdated: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    school: '중산중',
    notes: '',
  },
  {
    id: '5',
    name: '브레드보드 (Half Size)',
    category: '단품',
    quantity: 120,
    location: '보관함 5',
    status: ItemStatus.IN_STOCK,
    lastUpdated: new Date().toISOString(),
    school: '이음초',
    notes: '',
  },
];
